server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*" 
  info:
    os:
      enabled: true
    java:
      enabled: true            
                   
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: DEBUG
#    software.amazon.awssdk: DEBUG
    
aws:
  dynamodb:
    dynamodblocal:
      port: 18000