server:
  port: 8000
# Tomcat metrics enabled
# Spring Cloud for AWS Micrometer CloudWatch Metrics Integration Enabled if local testing is required
#  tomcat:
#    mbeanregistry:
#      enabled: true

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*" 
  info:
    os:
      enabled: true
    java:
      enabled: true
# Spring Cloud for AWS Micrometer CloudWatch Metrics Integration Enabled if local testing is required
#  cloudwatch:
#    metrics:
#      export:
#        enabled: true
                         
logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
    com.example: DEBUG
    com.example.fw.web.aspect.LogAspect: TRACE		
#    software.amazon.awssdk: DEBUG
    
aws:
  dynamodb:
    dynamodblocal:
      port: 18000